[build]
    command = "npm run build"
    publish = "public"

[build.environment]
    HUGO_VERSION = "0.51"

[context.production.environment]
    HUGO_ENV = "production"
    NODE_ENV = "production"

[context.branch-deploy]
    command = "npm run build"
